// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CaptureProfile(arg1, arg2) {
  return window['go']['main']['App']['CaptureProfile'](arg1, arg2);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfile'](arg1, arg2);
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function OpenLiveDir(arg1) {
  return window['go']['main']['App']['OpenLiveDir'](arg1);
}

export function OpenLiveFile(arg1) {
  return window['go']['main']['App']['OpenLiveFile'](arg1);
}

export function OpenStoreDir() {
  return window['go']['main']['App']['OpenStoreDir']();
}

export function RecaptureProfile(arg1, arg2) {
  return window['go']['main']['App']['RecaptureProfile'](arg1, arg2);
}

export function RefreshUsage() {
  return window['go']['main']['App']['RefreshUsage']();
}

export function SwitchProfile(arg1, arg2) {
  return window['go']['main']['App']['SwitchProfile'](arg1, arg2);
}
