// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<Record<string, string>>;

export function CaptureProfile(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string,arg2:string):Promise<void>;

export function GetOverview():Promise<Array<main.CliView>>;

export function OpenLiveDir(arg1:string):Promise<void>;

export function OpenLiveFile(arg1:string):Promise<void>;

export function OpenStoreDir():Promise<void>;

export function RecaptureProfile(arg1:string,arg2:string):Promise<void>;

export function RefreshUsage():Promise<void>;

export function SwitchProfile(arg1:string,arg2:string):Promise<main.SwitchResult>;
